### ISSUE TITLE
Notes

### ISSUE THREAD

**Issue by Johnicholas** [willemlarsen/mobprogrammingrpg#10]
Ran this with 6 people. We had fun.

My observations from the organizer's perspective:
1. Playing Mob Programming (and organizing Mob Programming) requires a particular split of your attention: a tiny amount of your attention should go to actually solving the problem, and
a big part of your attention should go to mindful attention to HOW you solve the problem - including watching for occasions to mark XP, and occasions to achieve a badge.
2. The organizer has a particular responsibility to MODEL this split,
and probably the way to model it is to be big-and-visible-and-happy in marking your own XP,
and in achieving your own badges. 

Other people's comments from the debrief:
* It's very easy to forget to mark XP.
* The easy FizzBuzz problem may not let us do most of the actions; most of our time and problem-solving had to do with tooling and context, not the problem.
* Though on another hand, questions related to the tool are perhaps good, because that's real substantive learning, people actually learning things.
* If we were doing a harder problem, the 3-minute rotations might be frustrating.
* Maybe a TimeWizard role, someone particularly responsible for monitoring the time and calling the rotations, maybe with some discretion, such as "call rotation at a natural break point after 3 minutes but before 4 minutes, or at 4 minutes if there was no natural break point". The TimeWizard might also remind / nudge people to mark their own XP, when they make one of the appropriate moves.
* Maybe a natural place for the TimeWizard is after taking the Driver role? A comparatively easy and or quiet role after the intensity of first navigating and then driving, and someone who has just finished driving probably has all 3 level 1 roles.

**Comment by willemlarsen** [comment]
Thanks so much for feedback! Wouldn't the TimeWizard just be the facilitator? Or have you been joining in play as the facilitator rather than staying as observer?
