### ISSUE TITLE
Minus Points for loud mobbers?

### ISSUE THREAD

**Issue by peitor** [willemlarsen/mobprogrammingrpg#12]
An idea we came up with...  People can also loose experience.
For example when the mobbers are interrupting and loud.

**Comment by willemlarsen** [comment]
I appreciate the urge! I think for now we don't want punitive mechanics part of the game. You can playtest this idea and tell me how it goes, however!

**Comment by pinage404** [comment]
To avoid being punitive, maybe we can give points to people who help prevent people from: 

- monopolizes the word
- speak loudly
- interrupt other people who are talking
- encourage / help people who are not used to speaking in a group / shy
