### ISSUE TITLE
option for navigator to follow driver

### ISSUE THREAD

**Issue by awostenberg** [willemlarsen/mobprogrammingrpg#13]
(please close or delete me:  I am filed on https://github.com/dillonkearns/mobster/issues/64) -awostenberg)   

We wanted to use mobber.cc timer to play Willem Larsen's RPG "by the book" from paper sheets. Larsen instructions have driver becoming next navigator, e.g "The Driver moves to the right and becomes the new Navigator, the Navigator becomes a generic Mobber.".     But the mob timer has navigator becoming driver.

Therefore how about a setting option toggle in which either a) driver becomes next navigator or b) navigator becomes next driver?
![asbuiltNavigatorBecomesNextDriver](https://user-images.githubusercontent.com/151585/54837091-2ebfd600-4c8b-11e9-8de3-44019f135391.PNG)

**Comment by dillonkearns** [comment]
Thanks for the suggestion @awostenberg!

I prefer to be opinionated when there is a good case for a certain approach with Mobster. It helps guide teams to make the right choices naturally, and it eliminates lots of configuration options.

This should probably just be the default and only ordering for the rotation. That is, the person who was at the keyboard last rotation will always be the navigator next.

@willemlarsen I'd be curious to hear your thoughts on that idea, too.

**Comment by willemlarsen** [comment]
100% agree that starting with a strong opinion is the way to go and that whoever drove last navigates next. From experience I'd say this is the best place to start.

**Comment by willemlarsen** [comment]
By the way @awostenberg thanks for playing the game!
