### ISSUE TITLE
Non-gendered sponsor icon

### ISSUE THREAD

**Issue by jamesshore** [willemlarsen/mobprogrammingrpg#15]
Rather than using a large beard for the Sponsor role, how about a non-gendered image instead? (Or a less in-your-face one.)

Some suggestions:

* Awareness icon: https://game-icons.net/1x1/lorc/awareness.html (my favorite)
* Owl icon: https://game-icons.net/1x1/lorc/owl.html (but in India, owls are foolish, not wise)
* Wizard staff icon: https://game-icons.net/1x1/lorc/wizard-staff.html (the experienced traveler)
* Fairy icon: https://game-icons.net/1x1/delapouite/fairy.html (the wish granter)

**Comment by willemlarsen** [comment]
done! whew.
