### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by HadrienMP** [willemlarsen/mobprogrammingrpg#19]
Hi Willem, as you saw on Twitter, we are planning to play the mob programming RPG next week. A few things were unclear to us after reading the rules. Could you answer a few questions ?

How do you unlock the level 2 roles ? Is one level 1 badge enough ?
If a person unlock the level 2 roles, do they read the rolesheets during the turn or between two turns ?
If you finished for example the mobber rolesheet, and you contribute an idea, you win a XP point, but where do you put it ? The navigator ? The driver ? In other words, can you earn the driver badge by just being a very good mobber ?
When you are on the driver role, can you contribute an idea and win a mobber point ? Or are you expected to stay in the driver role ?
Do you have tips to facilitate it in remote ?

Kind regards,

Hadrian

**Comment by willemlarsen** [comment]
Hope I'm not answering this too late -
- Two roles of a given level must be finished to unlock badges for the next level for one person
-Rolesheets can be read any time once they are unlocked
-Once you've finished a rolesheet it's done, no more points, although you can get credit on other role sheets (see the XP section of role sheet for details).
-You can only earn driver points while driving; same with navigator. these are special positions in the rotation that have that special constraint.
-I don't have any specific tips to facilitate remote play - it's nice to have a very visible badge parking lot for completed badges though, however you can do that.
