### ISSUE TITLE
Playbook vs role

### ISSUE THREAD

**Issue by gbirke** [willemlarsen/mobprogrammingrpg#3]
Can you elaborate more on the "your playbook is separate from your position the the rotation" rule, especially in regards to experience points? The experience points create some incentive towards the behavior on the playbook and this incentive can also create some competitive atmosphere instead of a cooperative one. Which leads to tension when people score XP for their playbook when they are in a different role (especially problematic for the driver and navigator role).

My suggestions would be:
* Mention "cooperative-ness" vs "competitive-ness" in the facilitators handbook.
* Have a rule that navigator and driver roles can only score XP for the navigator and driver.

**Comment by willemlarsen** [comment]
Thanks for the feedback. I'm looking at the options.

**Comment by willemlarsen** [comment]
Okay, I've added the rule that navigator and driver roles can only score XP for those spots in the rotation. Thanks!
