### ISSUE TITLE
FizzBuzz kata

### ISSUE THREAD

**Issue by OvisMaximus** [willemlarsen/mobprogrammingrpg#4]
I am just planning to do this Kata with my team and I wondered about the description of the FizzBuzz Kata in the facilitators guide. As far as I know the rules, the resulting stream should be:

1, 2, Fizz, 4, Buzz, Fizz, 7, 8, Fizz, Buzz, 11, Fizz, 13, 14, FizzBuzz, 16, ...

You mentioned just the first occurence of Fizz, Buzz and FizzBuzz. Was that intentional and if yes, how are the rules?

**Comment by willemlarsen** [comment]
Whoops! @dzappold has corrected this in the raw text version of the facilitator's guide.
